package proxmox

import (
	"os"
	"os/exec"
	"strings"
	"testing"
)

func TestRenderRouterDHCPReservationsIsStableAndRejectsInvalidInputs(t *testing.T) {
	var content []byte
	var err error
	if content, err = renderRouterDHCPReservations([]SDNRouterDHCPReservation{
		{MAC: "02:11:22:33:44:66", Address: "192.0.2.11"},
		{MAC: "02:11:22:33:44:55", Address: "192.0.2.10"},
		{MAC: "02:11:22:33:44:55", Address: "192.0.2.10"},
		{MAC: "02:11:22:33:44:55", DUID: "00:03:00:01:02:11:22:33:44:55", Address: "2001:db8::10"},
	}); err != nil {
		t.Fatalf("render valid router reservations: %v", err)
	}
	var rendered string = string(content)
	if strings.Count(rendered, "dhcp-host=") != 0 || !strings.Contains(rendered, "02:11:22:33:44:55,192.0.2.10\n02:11:22:33:44:66,192.0.2.11\nid:00:03:00:01:02:11:22:33:44:55,[2001:db8::10]\n") {
		t.Fatalf("router reservation file was not canonical and deduplicated: %q", rendered)
	}
	for _, reservation := range []SDNRouterDHCPReservation{
		{MAC: "invalid", Address: "192.0.2.10"},
		{MAC: "02:11:22:33:44:55", Address: "2001:db8::10"},
		{MAC: "02:11:22:33:44:55", DUID: "00:03:00:01:02:11:22:33:44:66", Address: "2001:db8::10"},
		{MAC: "02:11:22:33:44:55", DUID: "00:03:00:01:02:11:22:33:44:55", Address: "192.0.2.10"},
	} {
		if _, err = renderRouterDHCPReservations([]SDNRouterDHCPReservation{reservation}); err == nil {
			t.Errorf("invalid router DHCP reservation accepted: %#v", reservation)
		}
	}
}

func TestRouterDHCPLeaseCleanupRemovesOnlyConflictingReservedLeases(t *testing.T) {
	var directory string = t.TempDir()
	var reservationFile string = directory + "/reservations"
	var leaseFile string = directory + "/leases"
	var reservations []byte = []byte("# Generated by Organesson\n02:11:22:33:44:55,192.0.2.10\nid:00:03:00:01:02:11:22:33:44:55,[2001:db8::10]\n")
	var leases []byte = []byte("1234 02:aa:bb:cc:dd:ee 192.0.2.10 * client\n1234 02:11:22:33:44:55 192.0.2.11 * client\n1234 02:11:22:33:44:55 192.0.2.10 * client\n1234 1 2001:db8::10 * 00:03:00:01:02:aa:bb:cc:dd:ee\n1234 1 2001:db8::11 * 00:03:00:01:02:11:22:33:44:55\n1234 1 2001:db8::10 * 00:03:00:01:02:11:22:33:44:55\n")
	if err := os.WriteFile(reservationFile, reservations, 0600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(leaseFile, leases, 0600); err != nil {
		t.Fatal(err)
	}
	var command *exec.Cmd = exec.Command("/bin/sh", "-c", routerDHCPLeaseCleanupCommand(leaseFile, reservationFile))
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("run DHCP lease cleanup script: %v: %s", err, output)
	}
	var actual []byte
	var err error
	if actual, err = os.ReadFile(leaseFile); err != nil {
		t.Fatal(err)
	}
	var expected []byte = []byte("1234 02:11:22:33:44:55 192.0.2.11 * client\n1234 02:11:22:33:44:55 192.0.2.10 * client\n1234 1 2001:db8::11 * 00:03:00:01:02:11:22:33:44:55\n1234 1 2001:db8::10 * 00:03:00:01:02:11:22:33:44:55\n")
	if string(actual) != string(expected) {
		t.Fatalf("lease cleanup produced unexpected result:\n%s", actual)
	}
}
