package proxmox

import (
	"context"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/z46-dev/organesson/backend/config"
)

// TestManagedSnapshotDriverWaitsForTasksAndRejectsUnmanagedNames verifies the lifecycle safety checks.
func TestManagedSnapshotDriverWaitsForTasksAndRejectsUnmanagedNames(t *testing.T) {
	var snapshotPresent bool = true
	var deletedSnapshots int
	var fakePVE *httptest.Server
	fakePVE = httptest.NewTLSServer(http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		switch {
		case request.Method == http.MethodGet && request.URL.Path == "/api2/json/cluster/status":
			writePVEData(response, []any{})
		case request.Method == http.MethodGet && request.URL.Path == "/api2/json/cluster/resources":
			writePVEData(response, []map[string]any{{"type": "qemu", "vmid": 900, "node": "pve1", "name": "managed-vm", "status": "stopped"}})
		case request.Method == http.MethodGet && request.URL.Path == "/api2/json/nodes/pve1/status":
			writePVEData(response, map[string]any{"node": "pve1", "status": "online"})
		case request.Method == http.MethodGet && strings.HasSuffix(request.URL.Path, "/qemu/900/status/current"):
			writePVEData(response, map[string]any{"vmid": 900, "name": "managed-vm", "status": "stopped"})
		case request.Method == http.MethodGet && strings.HasSuffix(request.URL.Path, "/qemu/900/config"):
			writePVEData(response, map[string]any{"name": "managed-vm", "description": "Organesson managed resource op-1"})
		case request.Method == http.MethodGet && strings.HasSuffix(request.URL.Path, "/snapshot/og-key/config"):
			if !snapshotPresent {
				response.WriteHeader(http.StatusNotFound)
				return
			}
			writePVEData(response, map[string]any{"description": "Organesson managed snapshot key"})
		case request.Method == http.MethodPost && strings.HasSuffix(request.URL.Path, "/snapshot/og-key/rollback"):
			writePVEData(response, "UPID:pve1:1:1:1:qmrollback:900:root@pam:")
		case request.Method == http.MethodDelete && strings.HasSuffix(request.URL.Path, "/snapshot/og-key"):
			deletedSnapshots++
			snapshotPresent = false
			writePVEData(response, "UPID:pve1:2:2:2:qmdelsnapshot:900:root@pam:")
		case request.Method == http.MethodGet && strings.Contains(request.URL.Path, "/tasks/UPID:"):
			writePVEData(response, map[string]any{"status": "stopped", "exitstatus": "OK"})
		default:
			t.Errorf("unexpected fake PVE request: %s %s", request.Method, request.URL.String())
			writePVEData(response, nil)
		}
	}))
	defer fakePVE.Close()

	var driver *apiVMSnapshotDriver = &apiVMSnapshotDriver{settings: config.ProxmoxConfiguration{
		APIURL: fakePVE.URL + "/api2/json", APITokenID: "test!organesson", APITokenSecret: "secret", InsecureSkipVerify: true,
	}}
	var ctx context.Context = context.Background()
	if err := driver.Restore(ctx, "pve1", "900", "op-1", "og-key", "key"); err != nil {
		t.Fatalf("restore managed snapshot: %v", err)
	}
	if err := driver.Delete(ctx, "pve1", "900", "op-1", "admin-snapshot", "key"); err == nil {
		t.Fatal("snapshot name not generated by Organesson should be rejected")
	}
	if err := driver.Delete(ctx, "pve1", "900", "op-1", "og-key", "key"); err != nil {
		t.Fatalf("delete managed snapshot: %v", err)
	}
	if deletedSnapshots != 1 {
		t.Fatalf("expected one managed snapshot deletion, got %d", deletedSnapshots)
	}
}
