agent: 1
boot: order=scsi0
cores: 2
cpu: x86-64-v2-AES
memory: 2048
meta: creation-qemu=11.0.3,ctime=1791094569
name: og-router-debian13-source
numa: 0
ostype: l26
parent: initial-setup-v1
scsi0: laas:106/vm-106-disk-0.qcow2,iothread=1,size=16G
scsihw: virtio-scsi-single
smbios1: uuid=48f89cf3-1dce-4970-b18f-efa2758147ab
sockets: 1
vmgenid: a934921c-5919-4000-bd78-c71707cbc2ae